project:
  type: website

website:
  title: "Yanhe Eddie Lu"
  navbar:
    left:
      - href: index.qmd
        text: me
      - href: cv.qmd
        text: vitae
      - href: repo/index.qmd
        text: repositories
  back-to-top-navigation: true
  google-analytics: "G-5K3G6929BP"
  sidebar:
      - contents:
        - section: "Repository"
          href: repo/index.qmd
          contents:
            - text: "Micro I: Utility Theory"
              href: repo/micro-u/index.qmd
              contents:
              - text: "Finite Outcomes"
                href: repo/micro-u/u1.qmd
              - text: "Infinite Outcomes"
                href: repo/micro-u/u2.qmd
              - text: "vNM Axioms"
                href: repo/micro-u/u3.qmd
              - text: "Risk Aversion"
                href: repo/micro-u/u4.qmd
              - text: "Afriat's Theorem"
                href: repo/micro-u/u5.qmd
              - text: "Stochastic Choice"
                href: repo/micro-u/u6.qmd
            - text: "Micro II: Game Theory"
              href: repo/micro-g/index.qmd
              contents:
              - text: "Normal-Form Games"
                href: repo/micro-g/g1.qmd
              - text: "Extensive-Form Games"
                href: repo/micro-g/g2.qmd
              - text: "Repeated Games"
                href: repo/micro-g/g3.qmd
              - text: "Bayesian Games"
                href: repo/micro-g/g4.qmd
              - text: "Perfect Bayesian Equilibrium"
                href: repo/micro-g/g5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: footer.html

publish:
  gh-pages:
    branch: gh-pages
    dir: _site
