project:
  type: website

website:
  title: "Yanhe Eddie Lu"
  navbar:
    left:
      - href: index.qmd
        text: me
      - href: cv.qmd
        text: vitae
      - href: repo/index.qmd
        text: repositories

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: footer.html



