project:
  type: website

website:
  title: "Yanhe Eddie Lu"
  navbar:
    background: light
    search: true
    left:
      - href: index.qmd
        text: me
      - href: cv.qmd
        text: vitae
      - href: repo/index.qmd
        text: repositories
  back-to-top-navigation: true
  google-analytics: "G-5K3G6929BP"
  sidebar:
      - contents:
        - section: "Repository"
          href: repo/index.qmd
          contents:
          - text: "Class Notes"
            href: repo/#class-notes
            contents:
            - text: "Microeconomics"
              href: repo/#microeconomics
              contents:
                - text: "Micro I: Utility Theory"
                  href: repo/micro-u/index.qmd
                  contents:
                  - text: "Finite Outcomes"
                    href: repo/micro-u/cpu1.qmd
                  - text: "Infinite Outcomes"
                    href: repo/micro-u/cpu2.qmd
                  - text: "vNM Axioms"
                    href: repo/micro-u/vnm.qmd
                  - text: "Risk Aversion"
                    href: repo/micro-u/risk.qmd
                  - text: "Afriat's Theorem"
                    href: repo/micro-u/afriat.qmd
                  - text: "Stochastic Choice"
                    href: repo/micro-u/stochastic.qmd
                - text: "Micro II: Game Theory"
                  href: repo/micro-g/index.qmd
                  contents:
                  - text: "Normal-Form Games"
                    href: repo/micro-g/normal.qmd
                  - text: "Extensive-Form Games"
                    href: repo/micro-g/extensive.qmd
                  - text: "Repeated Games"
                    href: repo/micro-g/repeated.qmd
                  - text: "Bayesian Games"
                    href: repo/micro-g/bayesian.qmd
                  - text: "Perfect Bayesian Equilibrium"
                    href: repo/micro-g/pbe.qmd
            - text: "Corporate Finance"
              href: repo/#corporate-finance
              contents:
              - text: "Corporate Finance Theory"
                href: repo/cf/index.qmd
                contents: 
                - text: "Capital Structure"
                  href: repo/cf/capital-structure.qmd
                # - text: "Agency Problems"
                #   href: repo/cf/agency.qmd
                # - text: "Asymmetric Information"
                #   href: repo/cf/asym-info.qmd
                # - text: "Financing under Asym. Info."
                #   href: repo/cf/fin-asym-info.qmd
                # - text: "Price Formation"
                #   href: repo/cf/price.qmd
                # - text: "Corporate Monitoring"
                #   href: repo/cf/corp-monitor.qmd
                # - text: "Contracting"
                #   href: repo/cf/contract.qmd
              - text: "M&A"
                href: repo/ma/index.qmd
                contents:
                - text: "Deal Design"
                  href: repo/ma/deal-design.qmd
                - text: "Deal Rationale"
                  href: repo/ma/deal-rationale.qmd
                - text: "Deal Process"
                  href: repo/ma/deal-process.qmd
                - text: "Takeover Strategies"
                  href: repo/ma/takeover.qmd
                - text: "Merger Model"
                  href: repo/ma/merger.qmd
                - text: "LBO Modeling"
                  href: repo/ma/lbo.qmd
                - text: "Deal Regulation"
                  href: repo/ma/deal-regulation.qmd
                - text: "Taxation"
                  href: repo/ma/tax.qmd
            - text: "Asset Pricing"
              href: repo/#asset-pricing
              contents:
              - text: "Asset Pricing Theory"
                href: repo/ap/index.qmd
                contents: 
                - text: "Consumption I"
                  href: repo/ap/cp1.qmd
                - text: "Consumption II"
                  href: repo/ap/cp2.qmd
                - text: "Contingent Claims"
                  href: repo/ap/cc.qmd
                - text: "Factor Models"
                  href: repo/ap/factor.qmd
                - text: "Macroeconomic Allocation"
                  href: repo/ap/allocation.qmd
              - text: "Stochastic Finance"
                href: repo/sc/index.qmd
                contents: 
                - text: "Discrete-Time Finance"
                  href: repo/sc/s1.qmd
            - text: "Math Foundations"
              href: repo/#math-foundations
              contents:
              - text: "Math Analysis (Baby Rudin)"
                href: repo/babyrudin/index.qmd
                contents:
                - text: "Real and Complex Number Systems"
                  href: repo/babyrudin/c1.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    include-after-body: footer.html

publish:
  gh-pages:
    branch: gh-pages
    dir: _site

callout-icon: false