---
title: "Curriculum Vitae"
sidebar: false
format:
  html:
    toc: true # Enables the side navbar
    toc-location: left # Positions the navbar on the left
    toc-depth: 2 # Includes up to second-level headings in the TOC
    css: styles.css # Optional for further styling
---

<div style="text-align: right; margin-bottom: 20px;">
  <a href="cv.pdf" target="_blank" style="text-decoration: none;">
    <i class="fas fa-file-pdf" style="font-size: 1.5em; color: #d32f2f;"></i> Open PDF
  </a>
</div>

## Basics
<table style="border-collapse: collapse; width: 100%;">
  <tr>
    <td><strong>Name</strong></td>
    <td>Yanhe <strong>Eddie *Lu*</strong> (鲁颜赫)</td>
  </tr>
    <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><strong>Residence</strong></td>
    <td>St. Louis, MO</td>
  </tr>
  <tr>
    <td><strong>Status</strong></td>
    <td>Post-Completion Opt</td>
  </tr>
</table>



## Education
- **M.S. in Business Analytics (Financial Technology)**  
  *Olin Business School, Washington University in St. Louis*  
  2023.08 - 2024.12  
  **GPA: 3.96/4.00** (1st)  
  **Honors:** Beta Gamma Sigma, Outstanding Student Award, Charles F. Knight Scholar  
  **PhD Courseworks:** Corporate Finance Theory (A, 1/5), Asset Pricing (A), Microeconomic Theory (A)

- **B.S. in International Economics & Financial Risk Management**  
  *Central University of Finance and Economics (CUFE)*  
  2019.08 - 2023.06  
  **GPA: 90.25/100**  
  Senior Thesis: Effects of Development Initiatives on Foreign Direct Investments


## Research Experience

- **Economics of Credit Products**  
  *Research Assistant* for Prof. Armando Gomes, WashU Olin  
  2025.01 - Present  

- **Empirical Mergers \& Acquisitions Dynamics**  
  *Research Assistant* for Prof. Brett Green, WashU Olin  
  2025.01 - Present    

- **Empirical Corporate Finance**  
  *Research Assistant* for Prof. Margarita Tsoutsoura, WashU Olin  
  2024.05 - Present  


- **Distinguishing LLM Authorship Using Linguistic Dimensions**  
  *Research Assistant* for Dr. Gerald Onwujekwe, WashU Olin  
  2024.01 - 2024.11  


- **International Institute of Green Finance, CUFE**  
  *Research Analyst*  
  2022.02 - 2022.06  


## Teaching Experience
#### Teaching Assistant
Olin Business School, Washington University  

- **Advanced Financial Management**  
  *Undergraduate, Spring 2025*  
  Instructor: Margarita Tsoutsoura / Grant Clayton

- **Advanced Corporate Finance I - Valuation**  
  *Graduate, Spring 2025*  
  Instructor: Yaron Leitner 

- **A/B Testing in Business and Social Science**  
  *Undergraduate/Graduate, Spring 2025*  
  Instructor: Xiang Hui 

- **Understanding & Conducting Business Experiments**  
  *Undergraduate, Spring 2025*  
  Instructor: Xiang Hui 

- **Advanced Corporate Finance II - Financing**  
  *Graduate, Fall 2024*  
  Instructor: Yaron Leitner

- **Financial Markets**  
  *Graduate, Fall 2024*  
  Instructor: Yaron Leitner

- **Machine Learning**  
  *Graduate, Spring/Fall 2024*  
  Instructors: Durai Sundaramoorthi / Gerald Onwujekwe

- **Capital Market and Financial Management**  
  *Undergraduate, Spring 2024*  
  Instructor: Koray Sayili



## Professional Experience

- **FICC Product Specialist**  
  *China International Capital Corporation*  
  2023.03 - 2023.06  

- **Capital Markets Intern**  
  *China International Capital Corporation*  
  2022.06 - 2022.12  

- **Investment Banking Intern**  
  *China Merchants Securities*  
  2022.02 - 2022.06  

- **Wealth & Asset Management Consulting Assistant**  
  *Ernst & Young*  
  2021.12 - 2022.01  





## Skills

- **Programming**  
  Python, R, Stata, MATLAB, SQL, SAS, AWS, Hive, LaTeX, Web Dev  

- **Languages**  
  **Mandarin**: Native  
  **English**: Professional Fluency  
  **French**: Conversational  

- **Communication**  
  Chinese National 2nd Prize in English Public Speaking  
  US Academic Decathlon Bronze Medal on Speaking  



## Personal Information
- Guitarist for over 10 years  
- Passionate home cook  
- Enjoys cycling, hiking, and running  
- Cat and Dog Parent