---
title: "Real and Complex Number Systems"
format:
  html:
    toc: true # Enables the side navbar
    toc-location: left # Positions the navbar on the left
    toc-depth: 4 # Includes up to second-level headings in the TOC
---
::: {.hidden}
$$
 \def\BB#1{{\mathbb{#1}}}
 \def\BF#1{{\mathbf{#1}}}
$$
:::

*yedlu, Spring 2025*

## Introduction and Rationale  

The introduction of real number set $\BB{R}$ arises from the discovery that the rational number system ($\BB{Q}$) is inadequate in many scenarios. "Irrational numbers" is then introduced to fill the gap and is often approximated by rational numbers.  

(Complex number set $\BB{C}$ is introduced to fill the gap of algebraic calculations on real numbers.)  

Here's an example that shows the need of extension from the rational number system.  

::: {.callout-tip title="Example 1 - Algebraic Imcompleteness"}
We now show that    

$$\begin{aligned}
  p^2 &= 2
\end{aligned}$$

is not satisfied by **any** $p \in \BB{Q}$.
:::

::: {.callout-warning collapse="true" title="Example 1 Solution"}

**Proof.** Assume such $p$ exists. Since $p \in \BB{Q}$, we can denote this as $p = m/n$ where $m, n$ are integers that are not both even and $n \neq 0$.  

Rewrite the equation:  

$$\begin{aligned}
  m^2 &= 2 n^2
\end{aligned}$$

This shows that $m^2$ is even.

Then, our first conjecture would be that $m$ is even:  

If $m$ is **odd**, then we can use

$$\begin{aligned}
  m &= 2k + 1, k \in \BB{N} \\
  \implies m^2 &= 4k^2 + 4k + 1
\end{aligned}$$

to show the contrapositive statement (if $m^2$ is even then $m$ is even) is true.

It follows that both sides are divisible by $4$ (if $m = 2k$ is divisible by 2 then $m^2 = 4k^2$ is divisible by 4), hence $n^2$ (divisible by 2) and eventually $n$ is even (using conjecture above).  

It all leads to a contradiction! Hence the equation is not satisfied by **any** $p \in \BB{Q}$. $\blacksquare$
:::


::: {.callout-tip title="Example 2 - Analytic Imcompleteness"}
The set

$$\begin{aligned}
  A = \left\{p \in \BB{Q} \mid p > 0, p^2 < 2\right\}
\end{aligned}$$

contains no largest number.
:::

::: {.callout-warning collapse="true" title="Example 2 Solution"}
**Proof.** Given any $p \in A$, let 

$$\begin{aligned}
  q &= p - \frac{p^2 - 2}{p + 2}
\end{aligned}$$

We first show that $q > p$ holds when $p \in A$. Observe that $p^2 - 2 < 0$ and $p + 2 > 0$. Therefore $\frac{p^2 - 2}{p + 2}$ < 0 and $q > p$ holds.  

Now we show that $q^2 < 2$:  

$$\begin{aligned}
  q^2 - 2 &= (p^2 - \frac{2p(p^2 - 2)}{p+2} + \frac{(p^2 - 2)^2}{(p+2)^2}) - 2 \\
  &= \frac{2(p^2 - 2)}{(p+2)^2} < 0
\end{aligned}$$

Thus $q \in A$ and $q > p$ always hold.  

$\blacksquare$
:::

## Conceptual Background  

We have shown that the real number set $\BB{R}$ is needed to solve some problems in rational number "calculations". Nevertheless, we would need some building blocks in order to **rigorously** define what real number set is.  

### Set Notations 
Let $A, B$ be sets.  

| Notation | Explanation |
| - | ------------------ |
| $A = \emptyset$ | **Empty Set**: $A$ has no elements. |
| $x \in A$ | $x$ is an element of $A$. |
| $x \notin A$ | $x$ is not an element of $A$. |
| $A \subset B$ | $\forall x \in A \implies x \in B$ |
| $A = B$ | $A \subset B \wedge B \subset A$ |


### Ordered Sets
This is a basic concept that can been seen anywhere (and is usually assumed to be a common fact). We will show how to define ordered sets rigorously.  

::: {.callout-note title="Definition - Ordered Sets"}
Let $S$ be a set and $<$ be a binary relation. If  

1. $\forall x, y \in S$, one and only one of the following statements is true:  
   - $x < y$
   - $x = y$
   - $y < x$;  

2. $\forall x, y, z \in S$, $x < z$ is true when:
   - $x < y$ and
   - $y < z$. 

We call $<$ an **order** of $S$ and $(S, <)$ an **ordered set**.

:::


### Boundness
We here define several (upper) bound properties in a rigorous way. Same arguments for lower bound properties.

::: {.callout-note title="Definition - Bounds"}
Let $E \subset S$. If there is $\beta \in S$ such that  

$$\begin{aligned}
  \beta \geq x, \quad \forall x \in E,
\end{aligned}$$

we say that $\beta$ is an **upper bound** of $E$. Set $E$ is bounded above by $\beta$.
:::

::: {.callout-note title="Least Upper Bound"}
Say $\beta$ is an upper bound of $E \subset S$. If for *any* upper bound of $E$, $\gamma$, we have  

$$\begin{aligned}
  \beta \leq \gamma,
\end{aligned}$$

then $\beta$ is the **least upper bound** of set $E$.

(Another way to define the least upper bound is to say any $b < \beta$ is not an upper bound of $E$.)
:::

::: {.callout-important title="Supremum/Infimum"}
The *least upper bound* of set $E$ can be also called as the **supremum** of $E$:

$$\begin{aligned}
  \sup E
\end{aligned}$$

The *greatest lower bound* of set $E$ can be also called as the **infimum** of $E$:  

$$\begin{aligned}
  \inf E
\end{aligned}$$
:::


## Least-Upper-Bound (LUB) Property
This property turns out to be useful in defining and understanding $\BB{R}$.  

::: {.callout-note title="Definition - LUB Property"}
Let $S$ be an ordered set. 

We say $S$ has LUB property if for any non-empty $E \subset S$ that has an upper bound, there is:

$$\begin{aligned}
  \sup E \in S
\end{aligned}$$

:::

Using our findings above, we can show that $\BB{Q}$ does not have the LUB property:  

::: {.callout-tip title="Example: LUB Property and $\BB{Q}$"}
Let  

$$\begin{aligned}
  A = \left\{p \in \BB{Q} \mid p > 0, p^2 < 2 \right\}
\end{aligned}$$

The non-empty set $A \subset \BB{Q}$ does not have a supremum in $\BB{Q}$.

:::

### Symmetry in Least-Upper-Boundness
::: {.callout-important title="Theorem"}
$S$ has the least-upper-bound property implies that $S$ also has the greatest-lower-bound property.  

This is equivalent to:  

Suppose $S$ is an ordered set with the LUB property. $B$ is an non-empty subset of $S$ which is bounded below (in $S$).  

Let $L$ be the set of *all* lower bounds of $B$.  

Then, 

$$\begin{aligned}
  \alpha &= \sup L
\end{aligned}$$

exists in $S$, and $\alpha = \inf B$. In particular, $\inf B \in S$.

:::

::: {.callout-caution collapse="true" title="Proof of Theorem"}
**Proof.** 

Since $B$ is bounded below in $S$, $L \neq \emptyset$. 

Every $x \in B$ is an upper bound of $L$, hence $L$ is bounded above. By the LUB property, $\exists \alpha = \sup L \in L \subset S$.  

Suppose, for the sake of contradiction, that $\alpha$ is *not* a lower bound of $B$. Then $\exists x \in B$ with $x < \alpha$.  

However, $x \in B$ is an upper bound of $L$ (from 1), so $\alpha \leq x$. This contradicts $x < \alpha$. 

Hence, $\alpha$ *must be* a lower bound of $B$ ($\alpha \in L$).

Let $\gamma$ be any lower bound of $B$ ($\gamma \in L$). Since $\alpha = \sup L$, we have $\gamma \leq \alpha$ always true.  

Therefore, $\alpha$ is the greatest element in $L$. By the definition, $\alpha = \inf B$.

Since $\alpha = \sup L \in S$ and $\alpha = \inf B$, $S$ also has the greatest-lower-bound property. $\blacksquare$
:::

## Fields
We've learnt rules on additions and multiplications since ages. But how to properly define operations and other related topics? The concept of fields comes in. 

::: {.callout-note title="Definition - Fields"}
A **field** is a set $F$ with two operations:  

- addition (+),
- multiplication ($\cdot$),
  
which satisfy "field axioms" (A)(M)(D).
:::

### Field Axioms
##### \(A\) Addition

|\# | Name | Description |
| --- | --- | ---------- |
| A1 | Closure | $x, y \in F \implies x+y \in F$ |
| A2 | Commutativity | $(\forall x,y \in F) \quad x+y = y+x$ |
| A3 | Associativity | $(\forall x,y,z \in F) \quad (x+y)+z = x+(y+z)$ |
| A4 | Identity | $(\exists 0 \in F)(\forall x \in F) \quad 0+x = x$ |
| A5 | Inverse | $(\forall x \in F)(\exists -x \in F)x+(-x) = 0$ |

##### \(M\) Multiplication

|\# | Name | Description |
| --- | --- | ---------- |
| M1 | Closure | $x, y \in F \implies xy \in F$ |
| M2 | Commutativity | $(\forall x,y \in F) \quad xy=yx$ |
| M3 | Associativity | $(\forall x,y,z \in F) \quad (xy)z = x(yz)$ |
| M4 | Identity | $(\exists 1 \in F)(\forall x \in F) \quad 1x = x$ |
| M5 | Inverse | $(\forall x \in F)(\exists \, 1/x \in F) \quad x \cdot 1/x = 1$ |

##### \(D\) The Distributive Law

For all $x,y,z \in F$:  

$$\begin{aligned}
  x(y+z) &= xy + xz
\end{aligned}$$

::: {.callout-tip title='Consequences of the Field Axioms'}
- $x + y = x + z \implies y = z$
- $x + y = x \implies y = 0$
- $x + y = 0 \implies y = -x$
- $-(-x) = x$
:::


