---
title: "Afriat's Theorem"
format:
  html:
    toc: true # Enables the side navbar
    toc-location: left # Positions the navbar on the left
    toc-depth: 4 # Includes up to second-level headings in the TOC
---

\* in conjunction with §4 of Microeconomics Foundation I (Kreps 2013)

*Y. Eddie Lu*, Fall 2024

## Recap

:::{.callout-caution title="Notations"}
- $X = \mathbb{R}^{n}_{+}$ be consumption bundles. A vector with $n$ non-negative elements.
- $B(p,m) = \{x \in X: p \cdot x \leq m\}$ be the budget set.
- $c(B(p,m))$ be the demand chosen by the consumer.
:::

Key: what to infer from **finite** number of actual choices?

## Concepts and Assumptions
### Locally Insatiable
::: {.callout-note title="Dfn: Locally Insatiable"}
For every bundle $x \in X$, for every $\epsilon > 0$, there exists $y \in X$ with $|x-y| < \epsilon$ and $y \succ x$.  

Intuition: a consumer would always accept if they are provided a bundle with slightly more stuff. 
::: 

::: {.callout-tip title="Lemma"}

If $\succsim$ is complete, transitive, locally insatiable; $x^*$ is chosen from the budget set $B(p,m)$, then  

- $x^* \succsim x$ for all $x$ with $p \cdot x = m$
- $x^* \succ x$ for all $x$ with $p \cdot x < m$.

:::

### GARP (Generalized Axioms of Revealed Preferences)
::: {.callout-note title="Dfn: GARP"}
Given a finite dataset:  

- p = ($p^1, ..., p^n$) as the price vector
- m = ($m^1, ..., m^n$) as the income/budget vector
- x = ($x^1, ..., x^n$) as the choice vector

with $p^i \cdot x^i \leq m^i$ for each $i$, we say that:  

- $x^i \succsim^d x^j$ when $p^i \cdot x^j \leq m^i$
- $x^i \succ^d x^j$ when $p^i \cdot x^j < m^i$
- $x^i \succsim^R x^j$ when $x^i \succsim^d x \succsim^d ... \succsim^d x^j$
- $x^i \succ^R x^j$ when $x^i \succsim^d ... \succ^d x \succsim^d ... \succsim^d x^j$  

The dataset satistify **GARP** if $x^i \not\succ^R x^i$ for every $i$.
:::

### Strictly Increasing Preference
::: {.callout-note title="Dfn: Strictly Increasing Preference"}
The preference $\succsim \subseteq \mathbb{R}^n_+ \times \mathbb{R}^n_+$ is strictly increasing if  

- $x_i \geq y_i$ for all $i$
- $x \neq y$

implies $x \succ y$. This $\succsim$ is automatically locally insatiable.
:::

### Convex Preference
::: {.callout-note title="Dfn: Convex Preference"}
The preference $\succsim \subseteq \mathbb{R}^n_+ \times \mathbb{R}^n_+$ is convex if  

- $x \succsim y$
- $\alpha \in [0,1]$

implies $\alpha x + (1-\alpha) y \succsim y$.
:::

## Afriat's Theorem
::: {.callout-important title="Afriat's Theorem"}
1. If dataset **violates** GARP, then there cannot exist a complete, transitive, and locally insatiable  $\succsim$ with $x^i \in c_{\succsim}(B(p^i, m^i))$.
2. If dataset **satisfies** GARP, then there exists a complete, transitive, locally insatiable, **strictly increasing, continuous, convex** $\succsim$ with $x^i \in c_{\succsim}(B(p^i, m^i))$.
:::

::: {.callout-caution collapse="true" title="Proof of (1)"}

Suppose we have a complete, transitive, and locally insatiable $\succsim$ with $x^i \in c_{\succsim}(B(p^i, m^i))$ for each $i = 1, ..., n$.

If we had a GARP violation, then $x^i \succ^R x^i$. This implies that:

$$x^i \succsim^d ... \succsim^d x^j \succ^d x^k \succsim^d ... \succsim^d x^i$$

$$\Rightarrow x^i \succsim ... \succsim x^j \succ x^k \succsim ... \succsim x^i$$

$\Rightarrow x^i \succ x^i$, which leads to a contradiction.  

$\blacksquare$
:::


## Proof of 2 (Afriat's Approach to Constructing Utility)
Suppose data $(p, m, x)$ satisfies $p^i \cdot x^i \leq m^i$ and GARP.

1. $p^i \cdot x^i = m^i$ for all $i$. 

::: {.callout-tip title="Intuition"}
Every choice must be preference-maximizing under budget constraint. If not, then there must be a better choice under this price $p$ and budget constraint $m$.
:::

::: {.callout-caution collapse="true" title="Proof"}

Assume to contrary that $p^i \cdot x^i < m^i$. Then by GARP, $x^i \succ^d x^i$, which implies that $x^i \succ^R x^i$, which creates a contradiction by violates GARP.  

:::

2. $|\{x^k: x^i \succ^R x^k\}| < |\{x^k: x^j \succ^R x^k\}| \Rightarrow p^i \cdot x^j > m^i$. 

::: {.callout-tip title="Intuition"}
A choice $x^j$ strictly more superior than the other choice $x^i$ should never be feasible under the condition where $x^i$ was chosen. If not, then the choice should be $x^j$ instead of $x^i$.
:::

::: {.callout-caution collapse="true" title="Proof"}

If $p^i \cdot x^j \leq m^i$, then according to GARP, $x^i \succsim^d x^j$. Then, $\{x^k: x^j \succ^R x^k\} \subseteq \{x^k: x^i \succ^R x^k\}$, which contradicts $\{x^k: x^i \succ^R x^k\}| < |\{x^k: x^j \succ^R x^k\}|$.

:::

3. $|\{x^k: x^i \succ^R x^k\}| \leq |\{x^k: x^j \succ^R x^k\}| \Rightarrow p^i \cdot x^j \geq m^i$. 

::: {.callout-tip title="Intuition"}
A choice $x^j$ at least as good as the other choice $x^i$ should never be strictly inferior when under price and budget constraint of $x^i$.
:::

::: {.callout-caution collapse="true" title="Proof"}

Assume to contrary that $p^i \cdot x^j < m^i$. Then it implies that $x^i \succ^d x^j$. Also by GARP, $x^j \in \{x^k: x^i \succ^R x^k\}$ and $x^j \in \{x^k: x^i \succ^R x^k\}$. Thus, $\{x^k: x^j \succ^R x^k\} \subsetneq \{x^k: x^i \succ^R x^k\}$, contradicting the assumption. 

:::

4. $\exists x^k: \forall i \quad x^k \not\succ^R x^i$

::: {.callout-tip title="Intuition"}
There must be a lowest-ranking choice that is never strictly prefered to any other choices. If not, there will exist a loop that violates transitivity.
:::

::: {.callout-caution collapse="true" title="Proof"}

Suppoose for all $x^k$, there exists $x^i$ such that $x^k \succ^R x^i$. Then it must be the case that the following chain with $2n+1$ elements: $x^1 \succ x^{j1} \succ x^{j2} \succ ... \succ x^{j2n}$. Since we are in a finite set with $n$ choice bundles, there must be somewhere, in between, that $x^k \succ x^k$ happens, which directly violates GARP.

:::

5. $\exists \, v^1, ..., v^n \in \mathbb{R} \quad \exists \, \alpha^1, ..., \alpha^n > 0 \quad \forall i, j \quad v^i \leq v^j + \alpha^j [p^j x^i - p^j x^j]$

::: {.callout-tip title="Intuition"}
We want to use $v^j$ as the baseline of utility. $\alpha^j$ controls the speed of moving the baseline.
:::

::: {.callout-caution collapse="true" title="Proof"}

By induction. When $n=1$, let $v^1 = 0$ and $\alpha^1 = 1$. Suppose this is true when we have $n$ choices. Now, denote $x^{n+1}$ as $x^{n+1} \not\succ^R x^i$ for every $i$. We can imply from the assumption that this statement is true for observation $1, ..., n$ that: 

$$\exists \, v^1, ..., v^n \in \mathbb{R} \quad \exists \, \alpha^1, ..., \alpha^n > 0 \quad \forall i, j \quad v^i \leq v^j + \alpha^j [p^j x^i - p^j x^j].$$

Define: $v^{n+1} = \min_{1 \leq j \leq n} v^j + \alpha^j [p^j x^{n+1} - p^j x^j]$. Since $|\{x^k: x^{n+1} \succ^R x^k\}| = 0$, we can say that $p^{n+1} x^j \geq m^{n+1} = p^{n+1} x^{n+1}$ for every $1 \leq j \leq n$.  

We assert that for $1 \leq j \leq n$, either $p^{n+1} x^j > m^{n+1} = p^{n+1} x^{n+1}$ or $p^{n+1} x^j = m^{n+1} = p^{n+1} x^{n+1}$ holds. 

- If $p^{n+1} x^j > m^{n+1} = p^{n+1} x^{n+1}$,  $p^{n+1} x^j - p^{n+1} x^{n+1} > 0$. Then there exists $\alpha^{n+1} > 0$ large enough such that $v^j \leq v^{n+1} + \alpha^{n+1} [p^{n+1} x^j - p^{n+1} x^{n+1}]$ holds.  
- If $p^{n+1} x^j = m^{n+1} = p^{n+1} x^{n+1}$, $p^{n+1} x^j - p^{n+1} x^{n+1} = 0$.  

Then, as long as $\alpha^{n+1} \in \mathbb{R}_{++}$, $v^j \leq v^{n+1} + \alpha^{n+1} [p^{n+1} x^j - p^{n+1} x^{n+1}] = v^{n+1}$ holds.

:::

6. Let $u(x) := \min_{1 \leq j \leq n} v^i + \alpha^i [p^i x - p^i x^i]$.  

::: {.callout-tip title="Intuition"}
This function yields a concave form.
:::

## Application: Giffin Goods
- Normal goods: $p_i \uparrow \quad \Rightarrow x^i \downarrow$
- Giffin goods: $p_i \uparrow \quad \Rightarrow x^i \uparrow$

One application of Afriat's theorem is prooving the existance of Giffin goods. Since an individual with observable Giffin goods purchasing behavior does not necessarily violate GARP, then there exists a preference relation that is complete, transitive, locally insatiable, continuous, strictly increasing, and convex that generates it.